services:
  - type: web
    name: your-service-name  # Replace with your desired service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.app:app --host 0.0.0.0 --port 10000 --reload"
    envVars:
      - key: PORT
        value: "10000"
